// <auto-generated />
using System;
using BackOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackOffice.Infrastructure.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
    [Migration("20251117141647_Initialisation")]
    partial class Initialisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminProfils");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminProfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChangementMotPasse")
                        .HasColumnType("bit");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Desactive")
                        .HasColumnType("bit");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfilId");

                    b.HasIndex("Compte")
                        .IsUnique();

                    b.ToTable("AdminUtilisateurs", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateur", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminProfil", null)
                        .WithMany("Utilisateurs")
                        .HasForeignKey("AdminProfilId");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfil", b =>
                {
                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
