// <auto-generated />
using System;
using BackOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackOffice.Infrastructure.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
    [Migration("20251121040506_Initialisation")]
    partial class Initialisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Page")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("adminAccess", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminConnexions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("datetime");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminConnexions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminEvenementsTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminEvenementsTypes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdEvenementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvenementType");

                    b.ToTable("adminJournal", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EventChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventConnexion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventImpression")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventModificationDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventOuverturePage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventSuppressionDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventValidation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalActivation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalDureeLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalLimitation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalTailleLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalTypeDureeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalTypeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LDAPAuthentificationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPAuthentificationNomDomaine")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("LDAPCreationAutoActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPCreationAutoCompte")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LDAPCreationAutoNomServeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LDAPCreationAutoPassword")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ReplicationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplicationCompte")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ReplicationNomServeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ReplicationPassword")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AdminOptions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminReporting", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChangementMotPasse")
                        .HasColumnType("bit");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime");

                    b.Property<bool>("Desactive")
                        .HasColumnType("bit");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Compte")
                        .IsUnique();

                    b.ToTable("AdminUtilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99e9e71c-5619-4029-9565-cedc4eb686e1"),
                            ChangementMotPasse = true,
                            Compte = "admin",
                            Desactive = false,
                            MotPasse = "$2a$11$fCM3iFack2OFvNImjHdDUufN2mgkH7s.Z8ZBldl5eny.02CYD/U6C",
                            Nom = "Administrateur",
                            Prenoms = "Système"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateurTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminUtilisateurTypes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Attestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDelivrance")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("attestations", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.CategorieEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("TarifControle")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifHomologation")
                        .HasColumnType("money");

                    b.Property<byte?>("TarifHomologationParLot")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TarifHomologationQuantiteParLot")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("categoriesEquipements", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Bp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactFonction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pays")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Ville")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireTexte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomInstructeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Equipement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Fabricant")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("IdCategorie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMotifRejet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProposition")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modele")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDemande")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("QuantiteEquipements")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdMotifRejet");

                    b.HasIndex("IdProposition");

                    b.ToTable("demandes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontantControle")
                        .HasColumnType("money");

                    b.Property<decimal>("MontantEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("MontantHomologation")
                        .HasColumnType("money");

                    b.Property<string>("PaiementMobileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("PaiementOk")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("devis", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("documentsDemandes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("documentsDossiers", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdAgentInstructeur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdModeReglement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStatut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdAgentInstructeur");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdModeReglement");

                    b.HasIndex("IdStatut");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.ModeReglement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("MobileBanking")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("modesReglements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5266d314-c2a7-46dc-b592-d5042c346541"),
                            Code = "Virement",
                            Libelle = "Virement bancaire",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("2aa47244-4cd2-4c9b-a2dc-c8c57e53d410"),
                            Code = "Cheque",
                            Libelle = "Chèque",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("b2e63f47-dbad-4292-bb4c-2ef2f6f09b96"),
                            Code = "Especes",
                            Libelle = "Espèces",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("77863094-0e5b-40ac-9ac1-cfa10f6d46fa"),
                            Code = "MobileBanking",
                            Libelle = "Paiement mobile",
                            MobileBanking = (byte)1
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.MotifRejet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("motifsRejets", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("statuts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b6c0126-9a9b-4e82-96f8-b785362a11e1"),
                            Code = "NouvelleDemande",
                            Libelle = "Nouvelle demande"
                        },
                        new
                        {
                            Id = new Guid("da816f4f-77ec-42b6-b2fb-e02c91e4474c"),
                            Code = "EnCoursInstruction",
                            Libelle = "En cours d'instruction"
                        },
                        new
                        {
                            Id = new Guid("4e35f925-c5d8-41a8-b8b1-ea3a6109d3b8"),
                            Code = "EnvoyePourApprobation",
                            Libelle = "Envoyé pour approbation"
                        },
                        new
                        {
                            Id = new Guid("a2c98529-ac01-447e-af03-627ffc8c21c8"),
                            Code = "ApprouveAttentePaiement",
                            Libelle = "Approuvé, en attente de paiement"
                        },
                        new
                        {
                            Id = new Guid("7534eab1-e74f-4cfa-93f3-c9fe2e7bbc62"),
                            Code = "Rejetee",
                            Libelle = "Rejetée"
                        },
                        new
                        {
                            Id = new Guid("33d264ec-6b37-49b8-837a-f2ac5e8709ae"),
                            Code = "EquipementNonSoumisAHomologation",
                            Libelle = "Équipement non soumis à homologation"
                        },
                        new
                        {
                            Id = new Guid("bf8e0dd0-f39a-4a70-9e8f-c2cc43f7dc07"),
                            Code = "ApprouvePaiementEffectue",
                            Libelle = "Approuvé, paiement effectué"
                        },
                        new
                        {
                            Id = new Guid("9025ffb0-dfcd-4e60-a57d-d39fc8e64bb4"),
                            Code = "ApprouveAttestationSignee",
                            Libelle = "Approuvé, attestation signée"
                        },
                        new
                        {
                            Id = new Guid("b89fac12-213e-45dd-90d1-cf301cf6629b"),
                            Code = "AnnulationInstruction",
                            Libelle = "Annulation de l'instruction"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminEvenementsTypes", "EvenementType")
                        .WithMany()
                        .HasForeignKey("IdEvenementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvenementType");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Attestation", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Attestations")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Commentaires")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.CategorieEquipement", "CategorieEquipement")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Demandes")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.MotifRejet", "MotifRejet")
                        .WithMany()
                        .HasForeignKey("IdMotifRejet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Proposition", "Proposition")
                        .WithMany()
                        .HasForeignKey("IdProposition")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieEquipement");

                    b.Navigation("Dossier");

                    b.Navigation("MotifRejet");

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Devis", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Devis")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("DocumentsDemandes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("DocumentsDossiers")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminUtilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdAgentInstructeur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.ModeReglement", "ModeReglement")
                        .WithMany()
                        .HasForeignKey("IdModeReglement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModeReglement");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("DocumentsDemandes");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Demandes");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
