// <auto-generated />
using System;
using BackOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackOffice.Infrastructure.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
    [Migration("20260115232109_InitialCreate")]
    partial class InitialCreate
========
    [Migration("20260116015256_BD_Commun")]
    partial class BD_Commun
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Page")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("adminAccess", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminConnexions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DateConnexion")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminConnexions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminEvenementsTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminEvenementsTypes", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("b55c5c5e-d9ab-4e03-9c87-1ee759b78b8d"),
========
                            Id = new Guid("fc3c239b-ed73-4006-9b7e-726fd29a3159"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "CREATION",
                            Libelle = "Création de données"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("e9044539-7569-4acb-a57b-c6d5bc43b22c"),
========
                            Id = new Guid("fea2e948-c9e0-4c47-9dbd-ed46e90fa020"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "MODIFICATION",
                            Libelle = "Modification de données"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("b0363238-0df7-4f10-ad98-7af1e6050a6f"),
========
                            Id = new Guid("4a0e9be1-df57-4c2e-a76e-aeb47783fc4e"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "SUPPRESSION",
                            Libelle = "Suppression de données"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("7d9b195a-85fb-461a-b1b8-9d7cef56c267"),
========
                            Id = new Guid("24b5d07d-7847-4434-bb38-4061c80a83f5"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "VALIDATION",
                            Libelle = "Validation de processus"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("29b79654-825c-48ea-a68d-eea2f37228ca"),
========
                            Id = new Guid("d2b6eb3d-528b-400c-b6f7-4151cc8a9c54"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "CONNEXION",
                            Libelle = "Modification"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("12f69dd5-53c9-402f-b0f5-2c172aa31941"),
========
                            Id = new Guid("938c7cba-675f-41e1-8b17-810ae57d945b"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "MODIFICATION",
                            Libelle = "Connexion utilisateur"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("3b9759fa-a318-48f8-8748-94432ff3ff8f"),
========
                            Id = new Guid("b91c6126-b966-4e2d-9a01-52429c0dc171"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "ATTRIBUTION",
                            Libelle = "Attribution de droits/profils"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("1f8825d4-1c04-4912-ac95-27a5fc2977a1"),
========
                            Id = new Guid("2ea99492-748e-4726-8ef6-b74c42d580ac"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "SECURITE",
                            Libelle = "Action de sécurité"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("4db66a2b-040b-40b6-8256-0962b0d363dd"),
========
                            Id = new Guid("22dd1750-493f-4778-977a-9e32950d39aa"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "COMMUNICATION",
                            Libelle = "Envoi de communication"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("0d462e1e-17c6-4562-b862-7ef621b2e893"),
========
                            Id = new Guid("823d8193-41d1-4046-86ca-c7c1623735ae"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "QUALIFICATION",
                            Libelle = "Qualification de données"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("DateEvenement")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEvenementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("IdEvenementType");

                    b.ToTable("adminJournal", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EventChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventConnexion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventImpression")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventModificationDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventOuverturePage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventSuppressionDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventValidation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalActivation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalDureeLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalLimitation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalTailleLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalTypeDureeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalTypeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LDAPAuthentificationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPAuthentificationNomDomaine")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("LDAPCreationAutoActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPCreationAutoCompte")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LDAPCreationAutoNomServeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LDAPCreationAutoPassword")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ReplicationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplicationCompte")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ReplicationNomServeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ReplicationPassword")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AdminOptions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfils", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminProfils", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAccess")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminProfilsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("IdProfil", "IdAccess");

                    b.HasIndex("AdminProfilsId");

                    b.HasIndex("IdAccess");

                    b.ToTable("adminProfilsAcces", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminProfilsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Utilisateur", "IdProfil");

                    b.HasIndex("AdminProfilsId");

                    b.HasIndex("IdProfil");

                    b.ToTable("adminProfilsUtilisateursLDAP", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminReporting", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminProfilsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChangementMotPasse")
                        .HasColumnType("bit");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<long?>("DerniereConnexion")
                        .HasColumnType("bigint");

                    b.Property<bool>("Desactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUtilisateurType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfilsId");

                    b.HasIndex("Compte")
                        .IsUnique();

                    b.HasIndex("IdProfil");

                    b.HasIndex("IdUtilisateurType");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("AdminUtilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ChangementMotPasse = true,
                            Compte = "admin",
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            DateCreation = 1768519266563L,
                            Desactive = false,
                            IdUtilisateurType = new Guid("7e5b7d94-4f5d-4eff-9983-c8f846d3cee6"),
                            MotPasse = "$2a$11$XvxddNJ/LlGVw9PInz9d9eu2lBQbI8Aqdw9ZefCKEPStTsQpWVHuO",
========
                            DateCreation = 1768528372604L,
                            Desactive = false,
                            IdUtilisateurType = new Guid("7e5b7d94-4f5d-4eff-9983-c8f846d3cee6"),
                            MotPasse = "$2a$11$Iw4fIyfoV4R94B.flokOuOfHuaO4R8HumcogYp4S5Utk/PK.D2B6W",
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Nom = "root",
                            Prenoms = "ARPCE",
                            UtilisateurCreation = "SYSTEM_SEED"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateurTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminUtilisateurTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e5b7d94-4f5d-4eff-9983-c8f846d3cee6"),
                            Libelle = "Administrateur"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("4819cd06-4b3e-4f52-8961-a081becc6d01"),
========
                            Id = new Guid("b8bdee6d-8eb0-4604-9247-5df7cf365f65"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Libelle = "Utilisateur Standard"
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("852c76e0-be36-456c-9ebe-4a0d01c71f8c"),
========
                            Id = new Guid("0b1c7de2-12a2-41cc-990b-06f98d69091e"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Libelle = "Auditeur"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Attestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long>("DateDelivrance")
                        .HasColumnType("bigint");

                    b.Property<long>("DateExpiration")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Donnees")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroSequentiel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.HasIndex("NumeroSequentiel");

                    b.ToTable("attestations", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.CategorieEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("FormuleHomologation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("FraisControle")
                        .HasColumnType("money");

                    b.Property<decimal?>("FraisEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("FraisHomologation")
                        .HasColumnType("money");

                    b.Property<byte?>("FraisHomologationParLot")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FraisHomologationQuantiteParLot")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("QuantiteReference")
                        .HasColumnType("int");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeEquipement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("categoriesEquipements", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactFonction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NiveauValidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Entreprise");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<long?>("VerificationTokenExpiry")
                        .HasColumnType("bigint");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireTexte")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("commentaire");

                    b.Property<long>("DateCommentaire")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomInstructeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Proposition")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("commentaires", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Equipement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EstHomologable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Fabricant")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("IdCategorie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMotifRejet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProposition")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modele")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDemande")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("money");

                    b.Property<int?>("QuantiteEquipements")
                        .HasColumnType("int");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdMotifRejet");

                    b.HasIndex("IdProposition");

                    b.ToTable("demandes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontantControle")
                        .HasColumnType("money");

                    b.Property<decimal>("MontantEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("MontantHomologation")
                        .HasColumnType("money");

                    b.Property<string>("PaiementMobileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("PaiementOk")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.HasIndex("IdDossier");

                    b.ToTable("devis", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("documentsDemandes", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("documentsDossiers", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<long>("DateOuverture")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdAgentInstructeur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdModeReglement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStatut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdAgentInstructeur");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdModeReglement");

                    b.HasIndex("IdStatut");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.ModeReglement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("MobileBanking")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("modesReglements", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("e45a4067-ee62-4c18-a245-47b5cefdfb3d"),
========
                            Id = new Guid("4df4a9bf-37c8-43d0-b77e-6e0648da441b"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "Virement",
                            Libelle = "Virement bancaire",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("f6a11c84-808c-4e03-99ab-aa7962f54382"),
========
                            Id = new Guid("1a0ea036-99eb-483a-a174-d12d78404789"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "Cheque",
                            Libelle = "Chèque",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("34afea13-fa09-4133-a182-09bd6d94ab8b"),
========
                            Id = new Guid("34a379c6-33c0-4db9-87ae-c3e443ffc7c8"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "Especes",
                            Libelle = "Espèces",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<<< HEAD:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260115232109_InitialCreate.Designer.cs
                            Id = new Guid("502e7b17-1dcf-4d80-af7a-32a772cc26a6"),
========
                            Id = new Guid("fb510894-8ada-4416-9bff-2638a1a85ca5"),
>>>>>>>> ca87ec4ca4efd14b292889e9df7b2e63b8e6a11a:arpce-homologation-backOffice/Arpce.Homologation.BackOffice/BackOffice.Infrastructure/Migrations/20260116015256_BD_Commun.Designer.cs
                            Code = "MobileBanking",
                            Libelle = "Paiement mobile",
                            MobileBanking = (byte)1
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.MotifRejet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("motifsRejets", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long>("DateEnvoi")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfilCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DateEnvoi");

                    b.HasIndex("IsBroadcast");

                    b.HasIndex("ProfilCode");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("DateCreation")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateModification")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("statuts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f1c2f69-5d8e-4ec8-a6a1-0aa1e1c5a201"),
                            Code = "NouveauDossier",
                            Libelle = "Nouvelle demande"
                        },
                        new
                        {
                            Id = new Guid("a7c55954-7b1c-4f43-9cc4-1f2af3cca202"),
                            Code = "RefusDossier",
                            Libelle = "Refus de la demande"
                        },
                        new
                        {
                            Id = new Guid("3b9ed3a1-1e24-4d0c-8f13-7c55c9baa203"),
                            Code = "Instruction",
                            Libelle = "En cours d'instruction"
                        },
                        new
                        {
                            Id = new Guid("0d4f6e52-ad8e-4b67-9a11-985b66dca204"),
                            Code = "ApprobationInstruction",
                            Libelle = "Envoyé pour approbation"
                        },
                        new
                        {
                            Id = new Guid("84c6d32b-1f44-4fbd-8c91-12e3b5e0a205"),
                            Code = "InstructionApprouve",
                            Libelle = "Instruction Approuvée"
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-4f78-9012-34567890a218"),
                            Code = "Echantillon",
                            Libelle = "En attente échantillon"
                        },
                        new
                        {
                            Id = new Guid("d62e63cb-4c2f-4e24-b5a2-8fae11e0a206"),
                            Code = "DevisCreer",
                            Libelle = "Devis créé"
                        },
                        new
                        {
                            Id = new Guid("ae906d70-a1c2-4b2a-8db7-b22c6d4ca207"),
                            Code = "DevisValideSC",
                            Libelle = "Devis validé par Chef Service"
                        },
                        new
                        {
                            Id = new Guid("fc01b3e8-82d8-4e55-953f-0fc9edb2a208"),
                            Code = "DevisValideTr",
                            Libelle = "Devis validé par Trésorerie"
                        },
                        new
                        {
                            Id = new Guid("ccf4f5b7-8be7-4f01-9c09-fa5522d6a209"),
                            Code = "DevisEmit",
                            Libelle = "Devis émis"
                        },
                        new
                        {
                            Id = new Guid("8c2bc784-06a3-4d73-a9f4-5f6d94a7a210"),
                            Code = "DevisValide",
                            Libelle = "Devis validé par client"
                        },
                        new
                        {
                            Id = new Guid("cd3c7e21-6909-4a29-9f0e-90e9ac2da211"),
                            Code = "DevisRefuser",
                            Libelle = "Devis refusé par client"
                        },
                        new
                        {
                            Id = new Guid("0c47f66c-3ae3-4dbf-af5b-1b7eb3f2a213"),
                            Code = "PaiementRejete",
                            Libelle = "Paiement non accepté"
                        },
                        new
                        {
                            Id = new Guid("1a173ab7-6db7-4b9f-906e-a85352a4a212"),
                            Code = "DevisPaiement",
                            Libelle = "En attente de paiement"
                        },
                        new
                        {
                            Id = new Guid("5a6b7c8d-9e0f-1a2b-3c4d-5e6f70809000"),
                            Code = "EnPaiement",
                            Libelle = "Dossier en attente de paiement"
                        },
                        new
                        {
                            Id = new Guid("11223344-5566-7788-99aa-bbccddeeff00"),
                            Code = "PaiementBanque",
                            Libelle = "Dossier payé par la banque"
                        },
                        new
                        {
                            Id = new Guid("df4bb5aa-17d5-4c04-8545-48f59c59a214"),
                            Code = "PaiementExpirer",
                            Libelle = "Paiement expiré"
                        },
                        new
                        {
                            Id = new Guid("33b7bd1d-5901-4afe-be70-d4c10e3fa215"),
                            Code = "DossierPayer",
                            Libelle = "Paiement effectué"
                        },
                        new
                        {
                            Id = new Guid("aa11bb22-cc33-dd44-ee55-ff6600112233"),
                            Code = "Certification",
                            Libelle = "Certification initiée"
                        },
                        new
                        {
                            Id = new Guid("0e9a8bb4-7989-4eb8-9f21-4f9b7ffca216"),
                            Code = "DossierSignature",
                            Libelle = "Attestation en signature"
                        },
                        new
                        {
                            Id = new Guid("ed13c54b-5e63-4a0f-a0a7-332a7c27a217"),
                            Code = "DossierSigner",
                            Libelle = "Attestation signée"
                        });
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany()
                        .HasForeignKey("DossierId");

                    b.HasOne("BackOffice.Domain.Entities.AdminEvenementsTypes", "EvenementType")
                        .WithMany()
                        .HasForeignKey("IdEvenementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("EvenementType");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", null)
                        .WithMany("AdminProfilsAcces")
                        .HasForeignKey("AdminProfilsId");

                    b.HasOne("BackOffice.Domain.Entities.AdminAccess", "Access")
                        .WithMany()
                        .HasForeignKey("IdAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", null)
                        .WithMany("AdminProfilsUtilisateursLDAP")
                        .HasForeignKey("AdminProfilsId");

                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminUtilisateur", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", null)
                        .WithMany("Utilisateurs")
                        .HasForeignKey("AdminProfilsId");

                    b.HasOne("BackOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackOffice.Domain.Entities.AdminUtilisateurTypes", "UtilisateurType")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");

                    b.Navigation("UtilisateurType");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Attestation", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Attestations")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.CategorieEquipement", "CategorieEquipement")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Demandes")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.MotifRejet", "MotifRejet")
                        .WithMany()
                        .HasForeignKey("IdMotifRejet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Proposition", "Proposition")
                        .WithMany()
                        .HasForeignKey("IdProposition")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieEquipement");

                    b.Navigation("Dossier");

                    b.Navigation("MotifRejet");

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Devis", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Devis")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Devis")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("DocumentsDemandes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("DocumentsDossiers")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("BackOffice.Domain.Entities.AdminUtilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdAgentInstructeur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackOffice.Domain.Entities.ModeReglement", "ModeReglement")
                        .WithMany()
                        .HasForeignKey("IdModeReglement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackOffice.Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModeReglement");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.AdminProfils", b =>
                {
                    b.Navigation("AdminProfilsAcces");

                    b.Navigation("AdminProfilsUtilisateursLDAP");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDemandes");
                });

            modelBuilder.Entity("BackOffice.Domain.Entities.Dossier", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Demandes");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
