// <auto-generated />
using System;
using FrontOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrontOffice.Infrastructure.Migrations
{
    [DbContext(typeof(FrontOfficeDbContext))]
    [Migration("20251122201229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontantControle")
                        .HasColumnType("money");

                    b.Property<decimal>("MontantEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("MontantHomologation")
                        .HasColumnType("money");

                    b.Property<string>("PaiementMobileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("PaiementOk")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("IdDemande");

                    b.ToTable("devis", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Page")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("adminAccess", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminConnexions", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Utilisateur", "DateConnexion");

                    b.ToTable("adminConnexions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminEvenementsTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminEvenementsTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdEvenementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvenementType");

                    b.ToTable("adminJournal", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EventChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventConnexion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventImpression")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventModificationDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventOuverturePage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventSuppressionDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventValidation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalActivation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalDureeLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalLimitation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalTailleLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalTypeDureeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalTypeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LDAPAuthentificationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPAuthentificationNomDomaine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("LDAPCreationAutoActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPCreationAutoCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ReplicationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplicationCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminOptions");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfils", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminProfils", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAccess")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("IdProfil", "IdAccess");

                    b.HasIndex("IdAccess");

                    b.ToTable("adminProfilsAcces", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Utilisateur", "IdProfil");

                    b.HasIndex("IdProfil");

                    b.ToTable("adminProfilsUtilisateursLDAP", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminReporting", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminUtilisateurTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUtilisateurType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfil");

                    b.HasIndex("IdUtilisateurType");

                    b.ToTable("adminUtilisateurs", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDelivrance")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("attestations", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.CategorieEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("TarifControle")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifHomologation")
                        .HasColumnType("money");

                    b.Property<byte?>("TarifHomologationParLot")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TarifHomologationQuantiteParLot")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("categoriesEquipements", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Bp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactFonction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pays")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireTexte")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("date");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomInstructeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Proposition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("commentaires", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Equipement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Fabricant")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("IdCategorie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMotifRejet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProposition")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modele")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDemande")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("QuantiteEquipements")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdMotifRejet");

                    b.HasIndex("IdProposition");

                    b.ToTable("demandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("documentsDemandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("documentsDossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdModeReglement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStatut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdModeReglement");

                    b.HasIndex("IdStatut");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.ModeReglement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("MobileBanking")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("modesReglements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d80eb16-97fc-43ec-bf5f-bfc0a48a8b40"),
                            Code = "Virement",
                            Libelle = "Virement bancaire",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("c67397f6-b926-445e-9919-4d5c3dc89093"),
                            Code = "Cheque",
                            Libelle = "Chèque",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("8746bbce-d9c8-4aad-baa0-2fd13ff37d9a"),
                            Code = "Especes",
                            Libelle = "Espèces",
                            MobileBanking = (byte)0
                        },
                        new
                        {
                            Id = new Guid("34343348-4535-4745-93b5-78dc23c989b3"),
                            Code = "MobileBanking",
                            Libelle = "Paiement mobile",
                            MobileBanking = (byte)1
                        });
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.MotifRejet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("motifsRejets", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("statuts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ba6d657-01c1-46d2-ba1c-7e3681d4f12e"),
                            Code = "NouvelleDemande",
                            Libelle = "Nouvelle demande"
                        },
                        new
                        {
                            Id = new Guid("200f0b99-d446-44b0-9833-32cceb7a4a91"),
                            Code = "EnCoursInstruction",
                            Libelle = "En cours d'instruction"
                        },
                        new
                        {
                            Id = new Guid("9d62cb00-b885-4e98-8090-b9b48efcf1c1"),
                            Code = "EnvoyePourApprobation",
                            Libelle = "Envoyé pour approbation"
                        },
                        new
                        {
                            Id = new Guid("f2327e5b-3364-4a22-b5f7-5e081d6c5d6e"),
                            Code = "ApprouveAttentePaiement",
                            Libelle = "Approuvé, en attente de paiement"
                        },
                        new
                        {
                            Id = new Guid("b2ed740f-28e7-4be1-85c8-9b62267d0c60"),
                            Code = "Rejetee",
                            Libelle = "Rejetée"
                        },
                        new
                        {
                            Id = new Guid("961c2dea-7235-45ef-a2d1-23598ab21b4c"),
                            Code = "EquipementNonSoumisAHomologation",
                            Libelle = "Équipement non soumis à homologation"
                        },
                        new
                        {
                            Id = new Guid("d7115803-79af-4f22-83db-7e5ad405f4c8"),
                            Code = "ApprouvePaiementEffectue",
                            Libelle = "Approuvé, paiement effectué"
                        },
                        new
                        {
                            Id = new Guid("470346ae-9acf-4e6b-9b38-1696d84a9adc"),
                            Code = "ApprouveAttestationSignee",
                            Libelle = "Approuvé, attestation signée"
                        },
                        new
                        {
                            Id = new Guid("c98e3ed2-d7ae-47dd-b8bf-1332b93bcc1d"),
                            Code = "AnnulationInstruction",
                            Libelle = "Annulation de l'instruction"
                        });
                });

            modelBuilder.Entity("Devis", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", null)
                        .WithMany("Devis")
                        .HasForeignKey("DossierId");

                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany()
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminEvenementsTypes", "EvenementType")
                        .WithMany()
                        .HasForeignKey("IdEvenementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvenementType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminAccess", "Access")
                        .WithMany()
                        .HasForeignKey("IdAccess")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.AdminUtilisateurTypes", "UtilisateurType")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");

                    b.Navigation("UtilisateurType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Attestations")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.CategorieEquipement", "CategorieEquipement")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Demandes")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.MotifRejet", "MotifRejet")
                        .WithMany()
                        .HasForeignKey("IdMotifRejet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Proposition", "Proposition")
                        .WithMany()
                        .HasForeignKey("IdProposition")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieEquipement");

                    b.Navigation("Dossier");

                    b.Navigation("MotifRejet");

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("DocumentsDemandes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("DocumentsDossiers")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.ModeReglement", "ModeReglement")
                        .WithMany()
                        .HasForeignKey("IdModeReglement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModeReglement");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("DocumentsDemandes");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Demandes");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
