// <auto-generated />
using System;
using FrontOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrontOffice.Infrastructure.Migrations
{
    [DbContext(typeof(FrontOfficeDbContext))]
    partial class FrontOfficeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontantControle")
                        .HasColumnType("money");

                    b.Property<decimal>("MontantEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("MontantHomologation")
                        .HasColumnType("money");

                    b.Property<string>("PaiementMobileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("PaiementOk")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("IdDemande");

                    b.ToTable("devis", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Page")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("adminAccess", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminConnexions", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Utilisateur", "DateConnexion");

                    b.ToTable("adminConnexions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminEvenementsTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminEvenementsTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdEvenementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvenementType");

                    b.ToTable("adminJournal", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EventChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventConnexion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventImpression")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventModificationDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventOuverturePage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventSuppressionDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventValidation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalActivation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalDureeLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalLimitation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalTailleLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalTypeDureeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalTypeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LDAPAuthentificationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPAuthentificationNomDomaine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("LDAPCreationAutoActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPCreationAutoCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ReplicationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplicationCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminOptions");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfils", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminProfils", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAccess")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("IdProfil", "IdAccess");

                    b.HasIndex("IdAccess");

                    b.ToTable("adminProfilsAcces", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Utilisateur", "IdProfil");

                    b.HasIndex("IdProfil");

                    b.ToTable("adminProfilsUtilisateursLDAP", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminReporting", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminUtilisateurTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUtilisateurType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfil");

                    b.HasIndex("IdUtilisateurType");

                    b.ToTable("adminUtilisateurs", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDelivrance")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("attestations", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.CategorieEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("TarifControle")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifHomologation")
                        .HasColumnType("money");

                    b.Property<byte?>("TarifHomologationParLot")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TarifHomologationQuantiteParLot")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("categoriesEquipements", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactFonction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NiveauValidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Entreprise");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireTexte")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("date");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomInstructeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Proposition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("commentaires", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Equipement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EstHomologable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Fabricant")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("IdCategorie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMotifRejet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProposition")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modele")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDemande")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("money");

                    b.Property<int?>("QuantiteEquipements")
                        .HasColumnType("int");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdMotifRejet");

                    b.HasIndex("IdProposition");

                    b.ToTable("demandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("documentsDemandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("documentsDossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdModeReglement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStatut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdModeReglement");

                    b.HasIndex("IdStatut");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.ModeReglement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("MobileBanking")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("modesReglements", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("e2b2b684-d18d-4bae-a0b7-019b2703d5a2"),
=======
                            Id = new Guid("031db875-a68d-4697-8687-35be8c6c28b6"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "Virement",
                            Libelle = "Virement bancaire",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("a7dcf9ed-b28e-4421-9db1-786007dd9e54"),
=======
                            Id = new Guid("ad3911f4-4873-46bd-9125-d4c0bb798831"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "Cheque",
                            Libelle = "Chèque",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("06dc3b34-e707-4b02-8ab6-bf64a2aa96c8"),
=======
                            Id = new Guid("fc3c4acb-f5be-44f8-9f46-7da4206afe4c"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "Especes",
                            Libelle = "Espèces",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("db840f94-0213-41b4-bb15-439a515d9098"),
=======
                            Id = new Guid("6b6515cf-1625-4586-9438-c925108120f7"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "MobileBanking",
                            Libelle = "Paiement mobile",
                            MobileBanking = (byte)1
                        });
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.MotifRejet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("motifsRejets", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("statuts", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("773b6055-091f-4024-a715-f26dbdd84388"),
=======
                            Id = new Guid("ae6381ae-f0b6-4a71-979e-f0bd6ebb82fd"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "NouveauDossier",
                            Libelle = "Nouvelle demande"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("544c6d64-99ef-47f9-a6cc-7726a65390a5"),
=======
                            Id = new Guid("e2780ef6-15e1-498e-a569-8b0e1196fe7f"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "RefusDossier",
                            Libelle = "Refus de la demande"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("a2b8aff0-ed08-40fd-9e9c-6a534bbd53a7"),
=======
                            Id = new Guid("137ff980-8a78-49e5-9efb-adf2e617e001"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "Instruction",
                            Libelle = "En cours d'instruction"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("35113a9a-81ae-46d2-a127-c503f5e24e87"),
=======
                            Id = new Guid("793ba4e0-e91e-4a6e-8dc3-e4044f81a129"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "ApprobationInstruction",
                            Libelle = "Envoyé pour approbation"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("749bc3c1-8308-400b-bd5a-fdf032a0a716"),
=======
                            Id = new Guid("2ae5bd1d-79a2-428f-9dff-81eabdba87ee"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "InstructionApprouve",
                            Libelle = "Instruction Approuvée"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("37520795-1c96-4778-bdba-c033a1a5ce35"),
=======
                            Id = new Guid("1f92435c-363d-490c-940d-b4567fabe776"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisCreer",
                            Libelle = "Devis créé"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("4a12feb6-5ab3-46aa-b7f1-a2b81a55c492"),
=======
                            Id = new Guid("1036ecf2-426d-464d-9731-49895479e5aa"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisValideSC",
                            Libelle = "Devis validé par Chef Service"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("71bad125-4d41-4743-bcd3-d939b4364a25"),
=======
                            Id = new Guid("02b5b65f-c844-45df-ab1e-038e57172c24"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisValideTr",
                            Libelle = "Devis validé par Trésorerie"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("6fa6ab06-961b-430b-84ec-5618f3afb04f"),
=======
                            Id = new Guid("96f3cf57-7d7d-45f9-a8e3-8707e09fb91a"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisEmit",
                            Libelle = "Devis émis"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("b4ae938f-1cb3-4e6b-987b-efe6f70b26e5"),
=======
                            Id = new Guid("aaab4b1b-611e-4cce-9cb0-dd19d5747bce"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisValide",
                            Libelle = "Devis validé par client"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("c8e69820-0418-4537-8870-43d69c0d8de9"),
=======
                            Id = new Guid("7a705414-e990-471a-909a-3a0f4b0adc1d"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DevisRefuser",
                            Libelle = "Devis refusé par client"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("86dc85c6-fbb9-4100-b838-85123ef12c48"),
=======
                            Id = new Guid("630371a8-455d-493b-a154-5284260e525e"),
                            Code = "DevisPaiement",
                            Libelle = "En attente de paiement"
                        },
                        new
                        {
                            Id = new Guid("76db6f61-4677-4ac3-ad1b-51ea44b509a3"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "PaiementRejete",
                            Libelle = "Paiement non accepté"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("f368f5f9-2272-42c6-98da-6108fffb99bc"),
=======
                            Id = new Guid("a3b82ddd-41f8-43c1-b6e9-0c7f5a5cbf65"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "PaiementExpirer",
                            Libelle = "Paiement expiré"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("f0d0a419-ac31-4fb0-be77-216d5edc2005"),
=======
                            Id = new Guid("3e9ca4b5-edd7-4f37-ac26-30ceaaa3c01f"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DossierPayer",
                            Libelle = "Paiement effectué"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("b0c66819-1fd2-4926-b944-f4483229eb56"),
=======
                            Id = new Guid("430fe3be-6be0-4118-bd8c-a59a01e4b388"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DossierSignature",
                            Libelle = "Attestation en signature"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("92fdd850-65c4-4866-a94f-88c42551d0d2"),
=======
                            Id = new Guid("1b6d9b1d-f23b-4545-a8ea-04fae854d280"),
>>>>>>> 1d9561d315f3e08da5dce43b4f1fcf3112946eb9
                            Code = "DossierSigner",
                            Libelle = "Attestation signée"
                        });
                });

            modelBuilder.Entity("Devis", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", null)
                        .WithMany("Devis")
                        .HasForeignKey("DossierId");

                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Devis")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminEvenementsTypes", "EvenementType")
                        .WithMany()
                        .HasForeignKey("IdEvenementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvenementType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminAccess", "Access")
                        .WithMany()
                        .HasForeignKey("IdAccess")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.AdminUtilisateurTypes", "UtilisateurType")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");

                    b.Navigation("UtilisateurType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Attestations")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.CategorieEquipement", "CategorieEquipement")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Demandes")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.MotifRejet", "MotifRejet")
                        .WithMany()
                        .HasForeignKey("IdMotifRejet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Proposition", "Proposition")
                        .WithMany()
                        .HasForeignKey("IdProposition")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieEquipement");

                    b.Navigation("Dossier");

                    b.Navigation("MotifRejet");

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("DocumentsDemandes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("DocumentsDossiers")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.ModeReglement", "ModeReglement")
                        .WithMany()
                        .HasForeignKey("IdModeReglement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModeReglement");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDemandes");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Demandes");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
