// <auto-generated />
using System;
using FrontOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrontOffice.Infrastructure.Migrations
{
    [DbContext(typeof(FrontOfficeDbContext))]
    partial class FrontOfficeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontantControle")
                        .HasColumnType("money");

                    b.Property<decimal>("MontantEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("MontantHomologation")
                        .HasColumnType("money");

                    b.Property<string>("PaiementMobileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("PaiementOk")
                        .HasColumnType("tinyint");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("IdDemande");

                    b.ToTable("devis", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Page")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("adminAccess", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminConnexions", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Utilisateur", "DateConnexion");

                    b.ToTable("adminConnexions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminEvenementsTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminEvenementsTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdEvenementType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvenementType");

                    b.ToTable("adminJournal", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("EventChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventConnexion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventImpression")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventModificationDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventOuverturePage")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventSuppressionDonnees")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EventValidation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalActivation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalDureeLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalLimitation")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JournalTailleLimitation")
                        .HasColumnType("int");

                    b.Property<byte?>("JournalTypeDureeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("JournalTypeLimitation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LDAPAuthentificationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPAuthentificationNomDomaine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("LDAPCreationAutoActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("LDAPCreationAutoCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDAPCreationAutoPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ReplicationActivation")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReplicationCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationNomServeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplicationPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminOptions");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfils", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("adminProfils", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAccess")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Ajouter")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Imprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Supprimer")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Valider")
                        .HasColumnType("tinyint");

                    b.HasKey("IdProfil", "IdAccess");

                    b.HasIndex("IdAccess");

                    b.ToTable("adminProfilsAcces", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.Property<string>("Utilisateur")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Utilisateur", "IdProfil");

                    b.HasIndex("IdProfil");

                    b.ToTable("adminProfilsUtilisateursLDAP", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("Inactif")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminReporting", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("adminUtilisateurTypes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Compte")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("smalldatetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("IdProfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUtilisateurType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotPasse")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Prenoms")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfil");

                    b.HasIndex("IdUtilisateurType");

                    b.ToTable("adminUtilisateurs", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDelivrance")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("attestations", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.CategorieEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("TarifControle")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifEtude")
                        .HasColumnType("money");

                    b.Property<decimal?>("TarifHomologation")
                        .HasColumnType("money");

                    b.Property<byte?>("TarifHomologationParLot")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TarifHomologationQuantiteParLot")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("categoriesEquipements", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("ChangementMotPasse")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactFonction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactTelephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Desactive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotPasse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NiveauValidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RegistreCommerce")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Entreprise");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireTexte")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("date");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomInstructeur")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Proposition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("commentaires", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Equipement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EstHomologable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Fabricant")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("IdCategorie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMotifRejet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProposition")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marque")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Modele")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDemande")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("money");

                    b.Property<int?>("QuantiteEquipements")
                        .HasColumnType("int");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdDossier");

                    b.HasIndex("IdMotifRejet");

                    b.HasIndex("IdProposition");

                    b.ToTable("demandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDemande")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdDemande");

                    b.ToTable("documentsDemandes", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Donnees")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier");

                    b.ToTable("documentsDossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("date");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdModeReglement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStatut")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UtilisateurCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdModeReglement");

                    b.HasIndex("IdStatut");

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.ModeReglement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("MobileBanking")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("modesReglements", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("abae475b-4bbe-482e-a3c3-6f0a8fb8a39a"),
=======
                            Id = new Guid("2ecc1944-81ff-4d35-8485-64be414408c3"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "Virement",
                            Libelle = "Virement bancaire",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("d8fa333f-f101-4630-a7e0-d6deee470f93"),
=======
                            Id = new Guid("7d1f6160-8196-4547-a7a3-d7c36bb9c4d1"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "Cheque",
                            Libelle = "Chèque",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("c9eb67c7-1d96-483e-b60d-77bc0d2c4593"),
=======
                            Id = new Guid("24a61b71-1901-4669-92c9-ab2e8e56ef69"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "Especes",
                            Libelle = "Espèces",
                            MobileBanking = (byte)0
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("685f2103-b621-4960-9ae5-dbd236d9c53c"),
=======
                            Id = new Guid("98a79ac9-4e40-4e8e-ad1b-0687ecbe7608"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "MobileBanking",
                            Libelle = "Paiement mobile",
                            MobileBanking = (byte)1
                        });
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.MotifRejet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UtilisateurCreation")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilisateurModification")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("motifsRejets", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("propositions", (string)null);
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Statut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("statuts", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("6a88e65b-ad86-4f0d-b0c0-861bebafb134"),
=======
                            Id = new Guid("ca1432a2-3d79-4a63-aebd-b970de47ec8f"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "NouveauDossier",
                            Libelle = "Nouvelle demande"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("9e794884-3e62-478a-a1af-25f138ce209d"),
=======
                            Id = new Guid("9065791f-8d28-49d0-9c0f-1491ecec4a50"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "RefusDossier",
                            Libelle = "Refus de la demande"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("3370179a-d1ab-47c4-a9b4-3cf0e2ffbfdd"),
=======
                            Id = new Guid("150ee4be-59a6-4562-a9b0-165779d29549"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "Instruction",
                            Libelle = "En cours d'instruction"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("4aa91259-375e-43c8-bfa5-d71c5a2cbde3"),
=======
                            Id = new Guid("d61b3831-dcc6-4787-8ee2-95621da04b3f"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "ApprobationInstruction",
                            Libelle = "Envoyé pour approbation"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("0aefb8fa-13b6-4d05-b651-504b70f74c6d"),
=======
                            Id = new Guid("1594f36c-9f23-4435-863e-b6533e583978"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "InstructionApprouve",
                            Libelle = "Instruction Approuvée"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("08c53f08-3ae8-471e-820b-5e4aff3cd6e2"),
=======
                            Id = new Guid("2fec4af4-1145-4b2d-8bc9-88502603bdd0"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisCreer",
                            Libelle = "Devis créé"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("0a036a87-ca22-44d4-8c91-d8e6ea7dacab"),
=======
                            Id = new Guid("12aa6d02-63d0-422a-b78c-c14dc19b0031"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisValideSC",
                            Libelle = "Devis validé par Chef Service"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("89235ec6-e4a6-48f1-978d-78439dfd0838"),
=======
                            Id = new Guid("a39d0f24-d374-44e7-acfe-5b52bc197864"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisValideTr",
                            Libelle = "Devis validé par Trésorerie"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("fe75ed01-aabe-46ef-85d1-7eefac5eefe3"),
=======
                            Id = new Guid("62b38faf-d128-4cb2-8e94-4efaceb53216"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisEmit",
                            Libelle = "Devis émis"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("b0f9bd85-86c8-4d7e-8971-764793650401"),
=======
                            Id = new Guid("d4837a9c-1700-4ad8-ae01-082081a8be81"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisValide",
                            Libelle = "Devis validé par client"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("b87cebf9-3712-402d-9b84-797d9d3eba9f"),
=======
                            Id = new Guid("d8af2a46-3ed7-43c1-b850-ad273cf2ab81"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DevisRefuser",
                            Libelle = "Devis refusé par client"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("80b59ddc-8d18-4541-9fcc-fc191e947f00"),
=======
                            Id = new Guid("accbc8e6-031b-4e84-b38d-7a45fb9aa486"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "PaiementRejete",
                            Libelle = "Paiement non accepté"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("6086424b-a1d4-453f-82d2-e2db409d52a8"),
=======
                            Id = new Guid("0984b821-c0fe-4023-9e93-d22d2ee9ddc7"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "PaiementExpirer",
                            Libelle = "Paiement expiré"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("b0e36360-8f46-4518-9190-76ed0cb1a9e0"),
=======
                            Id = new Guid("9a1be6f7-561c-45ac-b7f2-85a57c06f582"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DossierPayer",
                            Libelle = "Paiement effectué"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("e69d8064-61b6-4068-a65c-c25c6cf838f2"),
=======
                            Id = new Guid("be7767fb-4b29-4b24-8eba-8134ff1ff248"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DossierSignature",
                            Libelle = "Attestation en signature"
                        },
                        new
                        {
<<<<<<< HEAD
                            Id = new Guid("a57e88cb-8d03-4788-9480-efaf905bf506"),
=======
                            Id = new Guid("176780e3-1fa7-4611-bfb1-0e19a1f434e7"),
>>>>>>> 1a85d91ce2689cd6397687313df3f1bb615cb6f5
                            Code = "DossierSigner",
                            Libelle = "Attestation signée"
                        });
                });

            modelBuilder.Entity("Devis", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", null)
                        .WithMany("Devis")
                        .HasForeignKey("DossierId");

                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Devis")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminJournal", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminEvenementsTypes", "EvenementType")
                        .WithMany()
                        .HasForeignKey("IdEvenementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvenementType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsAcces", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminAccess", "Access")
                        .WithMany()
                        .HasForeignKey("IdAccess")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminProfilsUtilisateursLDAP", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.AdminUtilisateurs", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.AdminProfils", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.AdminUtilisateurTypes", "UtilisateurType")
                        .WithMany()
                        .HasForeignKey("IdUtilisateurType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profil");

                    b.Navigation("UtilisateurType");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Attestation", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("Attestations")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Commentaires")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.CategorieEquipement", "CategorieEquipement")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("Demandes")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.MotifRejet", "MotifRejet")
                        .WithMany()
                        .HasForeignKey("IdMotifRejet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Proposition", "Proposition")
                        .WithMany()
                        .HasForeignKey("IdProposition")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategorieEquipement");

                    b.Navigation("Dossier");

                    b.Navigation("MotifRejet");

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDemande", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Demande", "Demande")
                        .WithMany("DocumentsDemandes")
                        .HasForeignKey("IdDemande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.DocumentDossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Dossier", "Dossier")
                        .WithMany("DocumentsDossiers")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("FrontOffice.Domain.Entities.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrontOffice.Domain.Entities.ModeReglement", "ModeReglement")
                        .WithMany()
                        .HasForeignKey("IdModeReglement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrontOffice.Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModeReglement");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Demande", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDemandes");
                });

            modelBuilder.Entity("FrontOffice.Domain.Entities.Dossier", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Demandes");

                    b.Navigation("Devis");

                    b.Navigation("DocumentsDossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
